version: '3'
services:
  rent-client:
    build: .
    container_name: rent-client
    restart: always
    ports:
      - 80:80
    environment:
      - REACT_APP_API=${REACT_APP_API-http://localhost:3000}
